# name: Hello World

# on: [push]

# jobs:
#   demo:
#     runs-on: windows-latest

#     steps:
#       - name: Print Hello World
#         run: echo "HELLO WORLD!"


name: Hello world

on:
  - push


jobs:
  demo:
    runs-on: windows-latest

    steps:
      - name: Printing Hello world...
        run: echo "how are you guys. Hello world"


